image: finschia/cw-gitpod:1.0.0

checkoutLocation: "cw-gitpod"
workspaceLocation: "./cw-gitpod/cosmwasm"

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - https://github.com/Finschia/cosmy-wasmy/releases/download/v2.3.1%2Bfinschia/cosmy-wasmy-2.3.1+finschia.vsix
    - tamasfe.even-better-toml

tasks:
  - name: Setup

    init: |
      ##
      # clone tutorials
      cd ..
      git clone https://github.com/Finschia/tutorials.git
      cd cosmwasm

      ##
      # generate workspace.
      cargo generate --git https://github.com/Finschia/cw-workspace.git --name tutorial --init -o

    command: |
      ##
      # run localnet and faucet
      cd ../tutorials/localnet/single
      docker-compose up -d finschia faucet
      cd ../../../cosmwasm

      ##
      # clear
      clear
